#pragma once
#include "prototype.h"

extern QC_BASIS_SET* QC_BASIS_DEF2_SVP_PTR;
extern QC_BASIS_SET* QC_BASIS_DEF2_TZVP_PTR;
extern QC_BASIS_SET* QC_BASIS_DEF2_TZVPP_PTR;
extern QC_BASIS_SET* QC_BASIS_DEF2_QZVP_PTR;
extern QC_BASIS_SET* QC_BASIS_DEF2_SVPD_PTR;
extern QC_BASIS_SET* QC_BASIS_DEF2_TZVPD_PTR;
extern QC_BASIS_SET* QC_BASIS_MA_DEF2_SVP_PTR;
extern QC_BASIS_SET* QC_BASIS_MA_DEF2_TZVP_PTR;
