layout(set = 0, binding = 0, std430) buffer CvValue { float cv_value[]; };
layout(set = 0, binding = 1, std430) buffer CrdGrads { Vec3 crd_grads[]; };
layout(set = 0, binding = 2, std430) buffer CvVirial { LTMat cv_virial[]; };
layout(set = 0, binding = 3, std430) buffer Frc { Vec3A frc[]; };
layout(set = 0, binding = 4, std430) buffer Energy { floatA energy[]; };
layout(set = 0, binding = 5, std430) buffer SelfEne { float self_ene[]; };
layout(set = 0, binding = 6, std430) buffer Virial { LTMatA virial[]; };
layout(push_constant) uniform Params
{
    int atom_numbers;
    float weight, reference, period;
    int ene_index;
    int need_potential;
}
pc;
void main()
{
    float dCV = cv_value[0] - pc.reference;
    if (pc.period > 0.0)
    {
        dCV = dCV - floor(dCV / pc.period + 0.5) * pc.period;
    }
    if (gl_WorkGroupID.x == 0u && gl_LocalInvocationIndex == 0u)
    {
        if (pc.need_potential != 0)
        {
            self_ene[pc.ene_index] = pc.weight * dCV * dCV;
            afadd(energy[0], pc.weight * dCV * dCV);
        }
        aadd_lt(virial[0], lt_scale(cv_virial[0], -2.0 * pc.weight * dCV));
    }
    uint stride = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    for (uint i = gl_GlobalInvocationID.x; i < uint(pc.atom_numbers);
         i += stride)
    {
        Vec3 force = v3_scale(crd_grads[i], -2.0 * pc.weight * dCV);
        aadd_v3(frc[i], force);
    }
}
