layout(set = 0, binding = 0, std430) buffer Crd { Vec3 crd[]; };
layout(set = 0, binding = 1, std430) buffer Value { float value[]; };
layout(set = 0, binding = 2, std430) buffer CrdGrads { Vec3 crd_grads[]; };
layout(set = 0, binding = 3, std430) buffer Virial { LTMat virial[]; };
layout(push_constant) uniform Params
{
    int atom0, atom1;
    Boundary boundary;
}
pc;
void main()
{
    Vec3 dr = get_displacement(crd[pc.atom1], crd[pc.atom0], pc.boundary);
    value[0] = dr.y;
    Vec3 drdx = Vec3(0.0, 1.0, 0.0);
    crd_grads[pc.atom1] = drdx;
    crd_grads[pc.atom0] = v3_neg(drdx);
    virial[0] = virial_from_force_dis(dr, drdx);
}
