layout(set = 0, binding = 0, std430) buffer Crd { Vec3 crd[]; };
layout(set = 0, binding = 1, std430) buffer SelfRadius { float self_radius[]; };
layout(set = 0, binding = 2, std430) buffer OtherRadius { float other_radius[]; };
layout(set = 0, binding = 3, std430) buffer EffectiveRadius { float effective_radius[]; };
layout(set = 0, binding = 4, std430) buffer DeDa { float de_da[]; };
layout(set = 0, binding = 5, std430) buffer Frc { Vec3A frc[]; };
layout(push_constant) uniform Params
{
    int atom_numbers;
    float cutoff_square;
}
pc;
void main()
{
    int atom_i = int(gl_GlobalInvocationID.x);
    int atom_j = int(gl_GlobalInvocationID.y);
    if (atom_i >= pc.atom_numbers || atom_j >= pc.atom_numbers ||
        atom_i == atom_j)
        return;
    Vec3 dr = v3_sub(crd[atom_j], crd[atom_i]);
    float dr2 = v3_dot(dr, dr);
    if (dr2 >= pc.cutoff_square) return;
    Sad1 R = sad1_var(sqrt(dr2));
    float self_radii = self_radius[atom_i];
    float other_radii = other_radius[atom_j];
    Sad1 inner_distance = sad1_add_c(R, -other_radii);
    Sad1 outer_distance = sad1_add_c(R, other_radii);
    Sad1 U = sad1_const(1.0);
    Sad1 L = sad1_const(1.0);
    if (self_radii <= inner_distance.val)
    {
        L = sad1_rdiv(1.0, inner_distance);
        U = sad1_rdiv(1.0, outer_distance);
    }
    else if (self_radii < outer_distance.val)
    {
        L = sad1_const(1.0 / self_radii);
        U = sad1_rdiv(1.0, outer_distance);
    }
    Sad1 t0 = sad1_mul(sad1_scale(R, 4.0), sad1_sub(L, U));
    Sad1 t1 = sad1_mul(sad1_mul(R, R),
                       sad1_sub(sad1_mul(U, U), sad1_mul(L, L)));
    Sad1 t2 = sad1_scale(sad1_log(sad1_div(U, L)), 2.0);
    Sad1 t3 = sad1_scale(sad1_sub(sad1_mul(L, L), sad1_mul(U, U)),
                         other_radii * other_radii);
    Sad1 temp = sad1_mul(sad1_rdiv(0.125, R),
                         sad1_add(sad1_add(t0, t1), sad1_add(t2, t3)));
    float reff = effective_radius[atom_i];
    Vec3 temp_frc =
        v3_scale(dr, reff * reff * temp.d0 * de_da[atom_i] / R.val);
    aadd_v3(frc[atom_i], temp_frc);
    aadd_v3(frc[atom_j], v3_neg(temp_frc));
}
