layout(set = 0, binding = 0, std430) buffer Crd { float crd[]; };
layout(set = 0, binding = 1, std430) buffer Vel { float vel[]; };
layout(push_constant) uniform Params
{
    int atom_numbers;
    float boundary;
    int low_boundary;
    int xyz;
}
pc;
void main()
{
    int atom_i = int(gl_GlobalInvocationID.x);
    if (atom_i >= pc.atom_numbers) return;
    int index = 3 * atom_i + pc.xyz;
    float delta = crd[index] - pc.boundary;
    if (pc.low_boundary != 0)
    {
        if (delta < 0.0) vel[index] = abs(vel[index]);
    }
    else
    {
        if (delta > 0.0) vel[index] = -abs(vel[index]);
    }
}
