layout(set = 0, binding = 0, std430) buffer Virial { LTMat virial[]; };
layout(set = 0, binding = 1, std430) buffer Stress { LTMat stress[]; };
layout(push_constant) uniform Params { float volume_inverse; } pc;
void main()
{
    if (gl_GlobalInvocationID.x != 0u) return;
    LTMat v = virial[0];
    stress[0].a11 += pc.volume_inverse * v.a11;
    stress[0].a21 += pc.volume_inverse * v.a21;
    stress[0].a22 += pc.volume_inverse * v.a22;
    stress[0].a31 += pc.volume_inverse * v.a31;
    stress[0].a32 += pc.volume_inverse * v.a32;
    stress[0].a33 += pc.volume_inverse * v.a33;
}
