layout(set = 0, binding = 0, std430) buffer GFrc { Vec3 g_frc[]; };
layout(set = 0, binding = 1, std430) buffer LFrc { Vec3 l_frc[]; };
layout(set = 0, binding = 2, std430) buffer IdGL { int atom_id_g_l[]; };
layout(push_constant) uniform Params { int n; } pc;
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uint(pc.n)) return;
    int l_id = atom_id_g_l[i];
    l_frc[l_id] = v3_add(l_frc[l_id], g_frc[i]);
}
