layout(set = 0, binding = 0, std430) buffer EnhancingEnergy { float enhancing_energy[]; };
layout(set = 0, binding = 1, std430) buffer Factor { float factor[]; };
layout(set = 0, binding = 2, std430) buffer DBias { float d_bias[]; };
layout(push_constant) uniform Params { float pe_a; float pe_b; } pc;
void main()
{
    if (gl_GlobalInvocationID.x != 0u) return;
    float ene = enhancing_energy[0];
    if (ene < pc.pe_b)
    {
        ene = pc.pe_b - ene;
        factor[0] =
            1.0 - ene * (2.0 * pc.pe_a + ene) / (pc.pe_a + ene) / (pc.pe_a + ene);
        d_bias[0] = ene * ene / (pc.pe_a + ene);
    }
    else
    {
        factor[0] = 1.0;
        d_bias[0] = 0.0;
    }
}
