struct VType2
{
    int virtual_atom;
    int from_1;
    int from_2;
    int from_3;
    float a;
    float b;
};
layout(set = 0, binding = 0, std430) buffer VInfo { VType2 v_info[]; };
layout(set = 0, binding = 1, std430) buffer Crd { Vec3 crd[]; };
layout(set = 0, binding = 2, std430) buffer Frc { Vec3 frc[]; };
layout(push_constant) uniform Params { int virtual_numbers; } pc;
void main()
{
    int i = int(gl_GlobalInvocationID.x);
    if (i >= pc.virtual_numbers) return;
    VType2 v_temp = v_info[i];
    Vec3 force_v = frc[v_temp.virtual_atom];
    aadd_v3(frc[v_temp.from_1],
            v3_scale(force_v, 1.0 - v_temp.a - v_temp.b));
    aadd_v3(frc[v_temp.from_2], v3_scale(force_v, v_temp.a));
    aadd_v3(frc[v_temp.from_3], v3_scale(force_v, v_temp.b));
    frc[v_temp.virtual_atom] = Vec3(0.0, 0.0, 0.0);
}
