struct VType0
{
    int virtual_atom;
    int from_1;
    float h;
};
layout(set = 0, binding = 0, std430) buffer VInfo { VType0 v_info[]; };
layout(set = 0, binding = 1, std430) buffer Crd { Vec3 crd[]; };
layout(set = 0, binding = 2, std430) buffer Frc { Vec3A frc[]; };
layout(push_constant) uniform Params { int virtual_numbers; } pc;
void main()
{
    int i = int(gl_GlobalInvocationID.x);
    if (i >= pc.virtual_numbers) return;
    VType0 v_temp = v_info[i];
    Vec3 force_v = to_v3(frc[v_temp.virtual_atom]);
    aadd_v3(frc[v_temp.from_1], Vec3(force_v.x, force_v.y, -force_v.z));
    frc[v_temp.virtual_atom] = from_v3(Vec3(0.0, 0.0, 0.0));
}
