# Generate vulkan_shader_sources.cpp from the GLSL kernel directory.
# Invoked as: cmake -DGLSL_DIR=<dir> -DOUT=<file> -P embed_vulkan_shaders.cmake

file(READ "${GLSL_DIR}/sponge_common.glsl" COMMON_SOURCE)
file(GLOB COMP_FILES "${GLSL_DIR}/*.comp")
list(SORT COMP_FILES)

set(CONTENT
    "// generated by embed_vulkan_shaders.cmake - do not edit
namespace sponge_vk
{
const char* CommonSource()
{
    static const char* source = R\"SPONGE_GLSL(${COMMON_SOURCE})SPONGE_GLSL\";
    return source;
}

struct KernelEntry
{
    const char* name;
    const char* source;
    int binding_count;
};

static const KernelEntry kKernelEntries[] = {
")

foreach(COMP_FILE ${COMP_FILES})
  get_filename_component(KERNEL_NAME ${COMP_FILE} NAME_WE)
  file(READ ${COMP_FILE} KERNEL_SOURCE)
  string(REGEX MATCHALL "binding[ \t]*=[ \t]*[0-9]+" BINDING_MATCHES
              "${KERNEL_SOURCE}")
  set(BINDING_COUNT 0)
  foreach(BINDING_MATCH ${BINDING_MATCHES})
    string(REGEX MATCH "[0-9]+" BINDING_INDEX "${BINDING_MATCH}")
    math(EXPR CANDIDATE "${BINDING_INDEX} + 1")
    if(CANDIDATE GREATER BINDING_COUNT)
      set(BINDING_COUNT ${CANDIDATE})
    endif()
  endforeach()
  string(APPEND CONTENT
         "    {\"${KERNEL_NAME}\", R\"SPONGE_GLSL(${KERNEL_SOURCE})SPONGE_GLSL\", ${BINDING_COUNT}},\n"
  )
endforeach()

string(
  APPEND
  CONTENT
  "};

int KernelCount()
{
    return sizeof(kKernelEntries) / sizeof(kKernelEntries[0]);
}
const char* KernelName(int id) { return kKernelEntries[id].name; }
const char* KernelSource(int id) { return kKernelEntries[id].source; }
int KernelBindingCount(int id)
{
    return kKernelEntries[id].binding_count;
}
}  // namespace sponge_vk
")

file(WRITE ${OUT} "${CONTENT}")
